let page=0,presentationSlides=[];
const number=(x,n=3)=>Number(x).toFixed(n),percent=x=>number(x*100,1)+'%';
function showSlide(next){
  page=Math.max(0,Math.min(presentationSlides.length-1,next));
  document.querySelectorAll('#slides section').forEach((s,i)=>s.hidden=i!==page);
  document.querySelector('#count').textContent=`0${page+1} / 0${presentationSlides.length}`;
  document.querySelector('#notes').textContent=presentationSlides[page]?.notes||'';
  document.querySelector('#previous').disabled=page===0;document.querySelector('#next').disabled=page===presentationSlides.length-1;
}
document.querySelector('#previous').onclick=()=>showSlide(page-1);document.querySelector('#next').onclick=()=>showSlide(page+1);
document.querySelector('#print').onclick=()=>window.print();
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();showSlide(page+1);}if(e.key==='ArrowLeft'){e.preventDefault();showSlide(page-1);}});
(async()=>{
 try{
  const [p,b,d,r,m]=await Promise.all(['intelligence/report.json','intelligence/battle_report.json','intelligence/decision_report.json','intelligence/R11.json','model.json'].map(async file=>{const response=await fetch('../artifacts/demo/'+file);if(!response.ok)throw new Error(file);return response.json();}));
  const s=r.snapshots.find(s=>s.driver==='NOR'&&s.lap===25),f=s.forecasts.find(f=>f.horizon===3),actual=r.evaluation.find(e=>e.driver==='NOR'&&e.issued_lap===25&&e.horizon===3);
  const st=s.stop_scenarios.HARD,rv=s.battles.find(b=>b.horizon===3),margin=3*st.step_s-rv.predicted_loss_s-1.5-.7,H=m.degradation_curves.practice.compounds.HARD;
  presentationSlides=[
   {html:`<div class="kicker">TrackShift 2026 / Aditya & Ruhani</div><h1>PITWALL</h1><h2>Tyre degradation intelligence</h2><p>Forecast the pace risk.<br>Price the response.</p>`,notes:'Open with the problem statement, then move straight into the product. This is a decision aid for a race engineer. Do not promise a measured position gain.'},
   {html:`<div class="kicker">01 / The tyre problem</div><h2>Tyre wear is hidden inside lap pace.</h2><div class="formula">Fuel + tyres + traffic + track evolution</div><div class="metrics"><div><strong class="warm">${number(H.naive.slope_s_per_lap)}</strong><span>Naive HARD slope / s per lap</span></div><div><strong>+${number(H.deconfounded.slope_s_per_lap)}</strong><span>After confounder correction</span></div></div><p>The practice curve still failed the race-transfer test. We validate race forecasts separately.</p><p class="foot">Historical research at tyre age 10, predating the replay traffic correction. Not a direct physical wear sensor.</p>`,notes:'Explain the sign error: fuel burn can make old tyres appear faster. Good in-sample identification is not enough. Our race evaluation is separate from the historical practice research. Source: model.json/degradation_curves.'},
   {html:`<div class="kicker">02 / Predict → advance → verify</div><h2>Lock a forecast. Then reveal the lap.</h2><p class="sub">Hungary / NOR / issue lap 25 → target lap 28</p><div class="metrics"><div><strong>${number(f.pace_s)}s</strong><span>Locked forecast</span></div><div><strong>${number(actual.actual_s)}s</strong><span>Recorded lap</span></div><div><strong>${number(Math.abs(f.pace_s-actual.actual_s))}s</strong><span>Absolute error</span></div></div><p>Persistence error: ${number(Math.abs(actual.baseline_s-actual.actual_s))}s. The forecast stays fixed as replay advances.</p><p class="foot">A named replay example, not an aggregate accuracy claim. Source: R11 intelligence snapshot and evaluation records.</p>`,notes:'Switch to the console: Present to jury → Predict & verify. Prediction is frozen at lap25; actual stays hidden until target28. Advance and score. Explain that the full benchmark, not this one example, establishes the measured improvement.'},
   {html:`<div class="kicker">03 / Undercut stress test</div><h2>Traffic can erase the attack margin.</h2><div class="formula">${number(3*st.step_s,2)}s tyre benefit − ${number(rv.predicted_loss_s,2)}s rival pace − 1.50s gap − 0.70s warm-up</div><div class="metrics"><div><strong>+${number(margin,2)}s</strong><span>Central margin / clean rejoin</span></div><div><strong class="warm">${number(margin-2,2)}s</strong><span>With 2s of rejoin traffic</span></div></div><p>Both uncertainty ranges cross zero. The engineer sees the fragile assumptions before committing.</p><p class="foot">Conditional scenario. Both cars stop; shared pit transit cancels. This does not predict an overtake.</p>`,notes:'In the app choose Price the undercut and click Add2s traffic. Read the waterfall aloud. The positive central value is not a pit command; the large empirical range shows why confidence would be unjustified. Source: R11/NOR/lap25 step and rival forecast.'},
   {html:`<div class="kicker">04 / Complete evaluation</div><h2>Measured improvement against baselines.</h2><div class="metrics"><div><strong>${number(p.improvement_pct,1)}%</strong><span>Less pace RMSE</span></div><div><strong>${number(b.improvement_pct,1)}%</strong><span>Less rival-time RMSE</span></div><div><strong>${percent(b.alerts.selected_s.precision)}</strong><span>Loss-alert precision</span></div></div><table><thead><tr><th>Feature</th><th>PITWALL</th><th>Baseline</th><th>Scored</th></tr></thead><tbody><tr><td>Lap forecast RMSE</td><td>${number(p.rmse_s)}s</td><td>${number(p.baseline_rmse_s)}s</td><td>${p.n.toLocaleString()}</td></tr><tr><td>Rival-time RMSE</td><td>${number(b.rmse_s)}s</td><td>${number(b.baseline_rmse_s)}s</td><td>${b.n.toLocaleString()}</td></tr><tr><td>Pre-stop pace RMSE</td><td>${number(d.rmse_s)}s</td><td>${number(d.baseline_rmse_s)}s</td><td>${d.n} stops</td></tr></tbody></table><p class="foot">R09–R12 are four reused evaluation races. Same-stint green continuations only. Stop-model gain is small; optimal pit strategy is unproven.</p>`,notes:'Pace scored/issued: '+p.scored_forecasts+'/'+p.issued_forecasts+'. Rival scored/issued: '+b.scored+'/'+b.issued+'. Baselines selected on development races. Loss-alert recall is '+percent(b.alerts.selected_s.recall)+' versus '+percent(b.alerts[b.baseline].recall)+'. All values come from the three intelligence reports, not manually entered headlines.'},
   {html:'<div class="kicker">05 / Working product</div><h2>A decision aid the engineer can inspect.</h2><div class="sequence">01 &nbsp; Predict and verify the next laps<br>02 &nbsp; Stress the undercut with traffic and rival response<br>03 &nbsp; Inspect the baseline, coverage and model limits</div><p>Measured forecast advantage.<br>Transparent strategy assumptions.<br>Grounded engineer briefing. Offline replay.</p><p class="foot">Use the app’s Present to jury walkthrough. Physical tyre life, optimal pit timing and realized positions gained remain unproven.</p>',notes:'Finish in the working app. Show that all features work without a cloud connection, that sensor gaps are visible, and that evidence can be downloaded. The strong claim is an auditable forecasting advantage and planning tool.'}
  ];
  document.querySelector('#slides').innerHTML=presentationSlides.map((s,i)=>`<section ${i?'hidden':''}>${s.html}</section>`).join('');showSlide(0);
 }catch(error){document.querySelector('#load-error').textContent='Evidence could not be loaded. Serve this folder over HTTP and check the artifacts: '+error.message;}
})();
